CREATE PROCEDURE [dbo].[PedidoActualizar]
	@IdPedidos INT,
	@Pedidos VARCHAR(50)
	
AS BEGIN
SET NOCOUNT ON

	BEGIN TRANSACTION TRASA

	BEGIN TRY
	-- AQUI VA EL CODIGO
		
		UPDATE Pedidos SET
		Pedidos = @Pedidos
		
		WHERE IdPedidos=@IdPedidos 
		
		COMMIT TRANSACTION TRASA
		
		SELECT 0 AS CodeError, '' AS MsgError

	END TRY

	BEGIN CATCH
		SELECT 
				ERROR_NUMBER() AS CodeError
			,	ERROR_MESSAGE() AS MsgError

			ROLLBACK TRANSACTION TRASA
	END CATCH
END
