CREATE TABLE [dbo].[Pedidos]
(
	IdPedidos INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Pedidos PRIMARY KEY CLUSTERED(IdPedidos),
	Pedidos VARCHAR(50) NOT NULL,
	EstadoPedidos BIT NOT NULL CONSTRAINT DF_Pedidos_EstadoPedidos DEFAULT(0),
)WITH (DATA_COMPRESSION = PAGE)